rnaveiras/postgres_exporter

collector/stat_activity.go

The new query will ignore entries that don't have a `backend_xid`.e.g. it ignores autovacuum...

Improve `postgres_stat_activity_oldest_xact_timestamp`

---

CHANGELOG.md
README.md
collector/stat_bgwriter.go

Monitor checkpoints and background writer process performance

Add collector `stat_bgwriter`

---

CHANGELOG.md
README.md
collector/stat_archiver.go

Collect some information regarding the two main events of the archiving process.

Add collector `stat_archiver`

---

README.md
collector/exporter.go
collector/stat_progress_vacuum.go

Add postgres_stat_vacuum_progress_* metrics for observability of vacuums.

RFC: Add vacuum metrics

---

.github/dependabot.yaml

Adds dependabot configuration for github action and gomod ecosystems

Add github dependabot

---

.errcheck_excludes.txt
.github/workflows/golangci-lint.yml
.golangci.yaml
Makefile
collector/stat_database.go
go.mod
go.sum
gokitadapter/adapter.go
postgres_exporter.go

Includes fixes and workflow to use locally

Add golangci-lint

---

.gitignore
.goreleaser.yml

Updated goreleaser configuration.

Updated goreleaser

---

.github/workflows/build.yaml

Add steps to build a container.

github-actions: Add container

---

.github/workflows/build.yaml

https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio

Updated github token permissions

---

.github/workflows/build.yaml
.github/workflows/golangci-lint.yml

This updates both workflows to trigger based on push and pull_request

Update github action event triggers

---

.github/workflows/build.yaml

I might revert this, after I automate cut releases

Build containers for PR

---

collector/exporter.go

This should be extracted to use flags

Ignore datname='cloudsqladmin' by default

---

.github/workflows/golangci-lint.yml
.golangci.yaml
postgres_exporter.go

Fixed the typo in the metricsPath

Fixed typo in the http handler

---

.github/workflows/build.yaml
.promu.yml

Update go version 1.20.3

---

.golangci.yaml
collector/exporter.go
collector/stat_replication.go

They are missing the settings for this check, might add it later

golang-ci; Disabled depguard

---

.github/workflows/build.yaml
.github/workflows/golangci-lint.yml

Change Nodejs runtime from node16 to node20

(chore): Update github actions

---

.promu.yml
Dockerfile

Update go releases, promu and alpine version

(chore) Update go release

---

.env
.mise.toml
renovate.json

- Add mise env, removed .env
- Update renovate config to pin github action digests

Add mise envs and update renovate

---

renovate.json

Add renovate configuration

---

.golangci.yaml
compose.yaml
docker/grafana/provisioning/datasources/prometheus.yaml
postgres_exporter.go

Add http graceful shutdown

---

collector/info.go

Ignore isInBackup for versions >= 15

---

.golangci.yaml
collector/exporter.go
postgres_exporter.go
tracelog.go

Update log entries to use best pratices

Add golangci sloglint, update logs entries

---

go.mod
go.sum

https://github.com/prometheus/client_golang/releases/tag/v1.21.1

Update update client-go v1.21.1

---

renovate.json

Avoid warnings by removed the inheritConfig

feat: Update renovate config
